### ISSUE TITLE
Rationale?

### ISSUE THREAD

**Issue by davidnormo** [getify/fpo#13]
The approach to this library is interesting but I would like to hear from you, @getify: what was the reason(s) behind it?

Some of the points of interest you pointed out or I've noticed so far are:
1. named-arguments replace argument position, meaning we need to remember names rather than position. (Which might be more intuitive for some)
2. named-arguments do away with placeholders for partial application!
3. variadic arguments aren't lost as a named-argument can be an array of any length (e.g. `compose({ fns: [] })`)

It would be great for you to expand on the above and say what you think are the advantages and draw backs to this approach! Thanks

**Comment by getify** [comment]
I think your summary is correct (and tracks pretty closely with what I say in the README, I think). I believe named-arguments is a more flexible API style, even if it's a bit noisier syntax wise. The tradeoff of remembering parameter names is worth it IMO.

I think having a name for each argument at the call-site makes that code a lot more readable. Prior to this idiom, I often found myself using code comments at a call site to name params, like this:

```js
ajax(
   /*url=*/ href,
   /*data*/= person,
);
```

With this style, the code comments aren't necessary anymore, because the named-arguments do the job well:

```js
ajax({
   url: href,
   data: person
});
```

**Comment by getify** [comment]
As for drawbacks, other than needing to remember the name of arguments, the biggest one I've run across so far: it may sometimes be the case that you have a mismatch in naming that makes using two functions together more awkward, requiring an adapter.

For example:

```js
function uppercase({ str }) { return str.toUpperCase(); }

FPO.map( { fn:uppercase, arr: ["hello","world"] } );
// TypeError!
```

Here, the uppercase function is expecting the argument to be named `str`, but `FPO.map(..)` calls its mapper function with the argument named `v`. So `str` is undefined, and the `toUpperCase()` method call fails.

The best option is to change the `uppercase(..)` function signature. But sometimes that won't be possible. So you then have to do a re-mapping of property names:

```js
FPO.map({
   fn: ({v}) => uppercase({ str: v }),
   arr: ["hello","world"]
});
// ["HELLO","WORLD"]
```

I'm thinking we need a helper method in FPO to aid in this re-mapping, maybe called `remap(..)`, for this purpose. It might look like:

```js
FPO.map({
   fn: FPO.remap( { fn: uppercase, args: {str: "v"} } ),
   arr: ["hello","world"]
});
// ["HELLO","WORLD"]
```

**Comment by getify** [comment]
I'm thinking we need a helper method in FPO to aid in this re-mapping, maybe called `remap(..)`, for this purpose. It might look like:

```js
FPO.map({
   fn: FPO.remap( { fn: uppercase, args: {str: "v"} } ),
   arr: ["hello","world"]
});
// ["HELLO","WORLD"]
```

If we also added a `reassoc(..)`:

```js
FPO.reassoc({ props: {foo: "bar"}, v:{foo: 42} } );
// { bar: 42 }
```

Then `remap(..)` is trivial to implement:

```js
function remap({ fn, args }) {
   return function remapped(argsObj){
      return fn( FPO.reassoc({ v: argsObj, props: args }) );
   };
}
```

**Comment by getify** [comment]
The other option, without needing to add anymore to the API, would be to use an `FPO.std.compose(..)` composition:

```js
FPO.map({
   fn: FPO.std.compose([
      uppercase,
      FPO.assoc( {prop: "str"} ),
   ]),
   arr: ["hello","world"]
});
// ["HELLO","WORLD"]
```

**Comment by getify** [comment]
Note: just added `reassoc(..)` in 3.1.0 (in e59c383e5af0d406594bee8f3f3c74dad45996dd)

**Comment by getify** [comment]
Closing for now. If you have any more questions or feedback, feel free to add them.
