### ISSUE TITLE
Should some named-args be renamed for more consistency?

### ISSUE THREAD

**Issue by getify** [getify/fpo#4]
Spun off from #3:

> [For `flatten(..)`, which uses `v` as its named argument...] what's the reasoning of not being `arr` in the first place?

Well, it's a judgement call and it could have gone either way. And TBH, I don't feel strongly that it has to be `v` over `arr`. But there's a bunch of other methods that take a single "value" argument to operate on, and in all those, we use `v`. There are other methods that take an array and call it `arr`, but those all take other params, too. For example, `reduce(..)` takes `v` for initial value and `arr` for the array.

FTR, my thinking was, is `flatten(..)` more like `flatMap(..)` or is it more like `pick(..)` or `setProp(..)`? I leaned to the latter instead of the former only because with `flatMap(..)`, the `arr` is operated on by a `fn`, but with `pick(..)`, the value (object in this case) is the main focus, so it's called `v`.

Of course, we have `zip(..)` which names its two params `arr1` and `arr2` instead of `v1` and `v2`. I almost did that, for the same reason as `v` for `flatten(..)`, but then I thought that `v1` and `v2` might be slightly confusing as "version 1" / "version 2".

So, I'm open to debate here, would like feedback. Should we:

1. Change `flatten(..)` to use `arr` instead of `v`?
2. Change `zip(..)` to use `v1` / `v2` instead of `arr1` / `arr2`?
3. ...any others?

**Comment by getify** [comment]
FWIW (maybe not much), methods that take their primary argument as `v` mean they themselves can be used as a mapper or predicate function, without adaptation. For example:

```js
var arr = [
   [[1,2],[3,4],5],
   [[6,7],[8,9]]
];

FPO.map( {fn: FPO.flatten, arr} );
// [ [1,2,3,4,5], [6,7,8,9] ]
```

**Comment by sebastiandedeyne** [comment]
My 2 cents—

Will it ever be possible to flatten or zip anything else than an array? If no, I'd say `arr` wins for clarity.

When talking to someone about code out loud, I wouldn't say "We need to flatten this value"—I'd say "We need to flatten this array".

**Comment by getify** [comment]
The more I work with the lib (and write tests), the more I think the generic `v` makes methods more composable with each other, and that's a good thing.

For example, `compose(..)` and `pipe(..)` now expect `{ v: .. }` style arguments instead of just the value by itself... that makes it super easy to use a composed function as a mapper-function for a `map(..)` call, for example, which is a common pattern.

I think we'll leave the methods as-is for now. But I'm certainly open to any feedback on a case-by-case basis.
